const translations = {
    es: {
      welcome: "Bienvenido a Vocate",
      description: `"Cultivada en la tierra, disfrutada en el alma"<br>
        Vocate nace en el corazón de Antioquia, fusionando tradición y creatividad para ofrecer una experiencia cervecera única.
        Esta bendita y refrescante cerveza artesanal destaca por su equilibrio perfecto entre cuerpo y sabor, con vibrantes notas cítricas que despiertan los sentidos.
        Con un 5% de alcohol, es ideal para quienes buscan disfrutar de una bebida ligera, pero con carácter.
        Su proceso de elaboración cuidadoso y el uso de ingredientes seleccionados garantizan una textura suave y un final limpio,
        convirtiéndola en una opción inolvidable para los amantes de la buena cerveza.`,
      price: "Precio: $13.000",
      carta: "Carta",
      llamar: "Llamar",
      comoLlegar: "Cómo llegar",
      cartaDigital: "Carta digital generada por",
      restaurante: "Restaurante Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Pedir"
    },
    en: {
      welcome: "Welcome to Vocate",
      description: `"Grown in the earth, enjoyed in the soul"<br>
        Vocate is born in the heart of Antioquia, blending tradition and creativity to offer a unique craft beer experience.
        This blessed and refreshing beer stands out for its perfect balance between body and flavor, with vibrant citrus notes that awaken the senses.
        With 5% alcohol, it's ideal for those seeking a light yet characterful drink.
        Its careful brewing process and selected ingredients ensure a smooth texture and clean finish,
        making it an unforgettable choice for true beer lovers.`,
      price: "Price: $13,000",
      carta: "Menu",
      llamar: "Call",
      comoLlegar: "Get Directions",
      cartaDigital: "Digital menu generated by",
      restaurante: "Vocate Restaurant",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Order"
    },
    de: {
      welcome: "Willkommen bei Vocate",
      description: `"In der Erde gewachsen, in der Seele genossen"<br>
        Vocate entsteht im Herzen von Antioquia und verbindet Tradition und Kreativität für ein einzigartiges Biererlebnis.
        Dieses gesegnete und erfrischende Bier zeichnet sich durch seine perfekte Balance zwischen Körper und Geschmack aus, mit lebendigen Zitrusnoten, die die Sinne wecken.
        Mit 5% Alkohol ist es ideal für diejenigen, die ein leichtes, aber charaktervolles Getränk suchen.
        Sein sorgfältiger Brauprozess und ausgewählte Zutaten garantieren eine weiche Textur und einen sauberen Abgang,
        was es zu einer unvergesslichen Wahl für echte Bierliebhaber macht.`,
      price: "Preis: $13.000",
      carta: "Karte",
      llamar: "Anrufen",
      comoLlegar: "Wegbeschreibung",
      cartaDigital: "Digitale Karte erstellt von",
      restaurante: "Restaurant Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Bestellen"
    },
    fr: {
      welcome: "Bienvenue chez Vocate",
      description: `"Cultivée dans la terre, savourée dans l'âme"<br>
        Vocate naît au cœur d'Antioquia, alliant tradition et créativité pour offrir une expérience brassicole unique.
        Cette bière bénie et rafraîchissante se distingue par son équilibre parfait entre corps et saveur, avec des notes vibrantes d'agrumes qui éveillent les sens.
        Avec 5% d'alcool, elle est idéale pour ceux qui recherchent une boisson légère mais avec du caractère.
        Son processus de brassage soigné et l'utilisation d'ingrédients sélectionnés garantissent une texture douce et une finale propre,
        en faisant un choix inoubliable pour les vrais amateurs de bière.`,
      price: "Prix: $13.000",
      carta: "Carte",
      llamar: "Appeler",
      comoLlegar: "Itinéraire",
      cartaDigital: "Carte numérique générée par",
      restaurante: "Restaurant Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Commander"
    }
};

function changeLanguage(lang) {
    localStorage.setItem("language", lang);
    updateTexts();
}

function updateTexts() {
    const lang = localStorage.getItem("language") || "es";
    const menuContent = document.getElementById("menu-content");
    if (menuContent) {
      menuContent.innerHTML = `
        <div class="menu-card">
          <h2>Cerveza Artesanal Vocate</h2>
          <p>${translations[lang].description}</p>
          <h3>${translations[lang].price}</h3>
          <button onclick="openModal('Cerveza Artesanal Vocate')">${translations[lang].pedir}</button>
        </div>
      `;
    }
    
    // Actualizar textos de la página principal
    const cartaButton = document.querySelector('button[onclick="goToMenu()"]');
    if (cartaButton) cartaButton.textContent = translations[lang].carta;
    
    const llamarLink = document.querySelector('a[href^="tel:"]');
    if (llamarLink) llamarLink.textContent = `📞 ${translations[lang].llamar}`;
    
    const mapsLink = document.querySelector('a[href^="https://www.google.com/maps"]');
    if (mapsLink) mapsLink.textContent = `📍 ${translations[lang].comoLlegar}`;
    
    const infoP = document.querySelector('.info p');
    if (infoP) infoP.innerHTML = `<strong>${translations[lang].restaurante}</strong><br>${translations[lang].direccion}`;
    
    const footerP = document.querySelector('footer p');
    if (footerP) footerP.innerHTML = `${translations[lang].cartaDigital} <span class="marca">Rezagoter</span>`;
}

function goToMenu() {
    window.location.href = "menu.html";
}

function openModal(productName) {
    document.getElementById("modal-product-name").innerText = productName;
    document.getElementById("order-modal").classList.remove("hidden");
}

function closeModal() {
    document.getElementById("order-modal").classList.add("hidden");
}

const telegramToken = "7640380344:AAEfQgNMn68tjc1yZ7Qo-uiz2MzogKMYMS4";
const chatId = "-4830084753";

document.getElementById("order-form").addEventListener("submit", function (e) {
    e.preventDefault();

    const name = document.getElementById("customer-name").value.trim();
    const table = document.getElementById("table-number").value.trim();
    const product = document.getElementById("modal-product-name").textContent.trim();

    if (!name || !table) {
        alert("Por favor completa todos los campos.");
        return;
    }

    const message = `🧾 *Nuevo pedido recibido:*\n🍽️ Producto: *${product}*\n👤 Nombre: *${name}*\n🪑 Mesa: *${table}*`;

    // Enviar mensaje a Telegram
    fetch(`https://api.telegram.org/bot${telegramToken}/sendMessage`, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            chat_id: chatId,
            text: message,
            parse_mode: "Markdown",
        }),
    })
        .then((response) => {
            if (response.ok) {
                alert("✅ Pedido enviado correctamente.");
                closeModal();
                document.getElementById("order-form").reset();
            } else {
                throw new Error("Error al enviar a Telegram.");
            }
        })
        .catch((error) => {
            console.error(error);
            alert("❌ No se pudo enviar el pedido. Intenta de nuevo.");
        });
});

// Asegurarse de que changeLanguage esté disponible globalmente
window.changeLanguage = changeLanguage;

document.addEventListener("DOMContentLoaded", function() {
    // Cargar el idioma guardado o usar español por defecto
    const savedLang = localStorage.getItem("language") || "es";
    updateTexts();
});
