const translations = {
    es: {
      welcome: "Bienvenido a Vocate",
      description: `"Cultivada en la tierra, disfrutada en el alma"<br>
        Vocate nace en el corazón de Antioquia, fusionando tradición y creatividad para ofrecer una experiencia cervecera única.
        Esta bendita y refrescante cerveza artesanal destaca por su equilibrio perfecto entre cuerpo y sabor, con vibrantes notas cítricas que despiertan los sentidos.
        Con un 5% de alcohol, es ideal para quienes buscan disfrutar de una bebida ligera, pero con carácter.
        Su proceso de elaboración cuidadoso y el uso de ingredientes seleccionados garantizan una textura suave y un final limpio,
        convirtiéndola en una opción inolvidable para los amantes de la buena cerveza.`,
      price: "Precio: $13.000",
      carta: "Carta",
      llamar: "Llamar",
      comoLlegar: "Cómo llegar",
      cartaDigital: "Carta digital generada por",
      restaurante: "Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Pedir",
      confirmarPedido: "Confirmar pedido"
    },
    en: {
      welcome: "Welcome to Vocate",
      description: `"Grown in the earth, enjoyed in the soul"<br>
        Vocate is born in the heart of Antioquia, blending tradition and creativity to offer a unique craft beer experience.
        This blessed and refreshing beer stands out for its perfect balance between body and flavor, with vibrant citrus notes that awaken the senses.
        With 5% alcohol, it's ideal for those seeking a light yet characterful drink.
        Its careful brewing process and selected ingredients ensure a smooth texture and clean finish,
        making it an unforgettable choice for true beer lovers.`,
      price: "Price: $13,000",
      carta: "Menu",
      llamar: "Call",
      comoLlegar: "Get Directions",
      cartaDigital: "Digital menu generated by",
      restaurante: "Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Order",
      confirmarPedido: "Confirm order"
    },
    de: {
      welcome: "Willkommen bei Vocate",
      description: `"In der Erde gewachsen, in der Seele genossen"<br>
        Vocate entsteht im Herzen von Antioquia und verbindet Tradition und Kreativität für ein einzigartiges Biererlebnis.
        Dieses gesegnete und erfrischende Bier zeichnet sich durch seine perfekte Balance zwischen Körper und Geschmack aus, mit lebendigen Zitrusnoten, die die Sinne wecken.
        Mit 5% Alkohol ist es ideal für diejenigen, die ein leichtes, aber charaktervolles Getränk suchen.
        Sein sorgfältiger Brauprozess und ausgewählte Zutaten garantieren eine weiche Textur und einen sauberen Abgang,
        was es zu einer unvergesslichen Wahl für echte Bierliebhaber macht.`,
      price: "Preis: $13.000",
      carta: "Karte",
      llamar: "Anrufen",
      comoLlegar: "Wegbeschreibung",
      cartaDigital: "Digitale Karte erstellt von",
      restaurante: "Restaurant",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Bestellen",
      confirmarPedido: "Bestellung bestätigen"
    },
    fr: {
      welcome: "Bienvenue chez Vocate",
      description: `"Cultivée dans la terre, savourée dans l'âme"<br>
        Vocate naît au cœur d'Antioquia, alliant tradition et créativité pour offrir une expérience brassicole unique.
        Cette bière bénie et rafraîchissante se distingue par son équilibre parfait entre corps et saveur, avec des notes vibrantes d'agrumes qui éveillent les sens.
        Avec 5% d'alcool, elle est idéale pour ceux qui recherchent une boisson légère mais avec du caractère.
        Son processus de brassage soigné et l'utilisation d'ingrédients sélectionnés garantissent une texture douce et une finale propre,
        en faisant un choix inoubliable pour les vrais amateurs de bière.`,
      price: "Prix: $13.000",
      carta: "Carte",
      llamar: "Appeler",
      comoLlegar: "Itinéraire",
      cartaDigital: "Carte numérique générée par",
      restaurante: "Vocate",
      direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
      pedir: "Commander",
      confirmarPedido: "confirmer la commande"
    }
};

function changeLanguage(lang) {
  localStorage.setItem("language", lang);
  updateTexts();
}

function updateTexts() {
  const lang = localStorage.getItem("language") || "es";
  const cartaButton = document.querySelector('button[onclick="goToMenu()"]');
  if (cartaButton) cartaButton.textContent = translations[lang].carta;

  const llamarLink = document.querySelector('a[href^="tel:"]');
  if (llamarLink) llamarLink.textContent = `📞 ${translations[lang].llamar}`;

  const mapsLink = document.querySelector('a[href^="https://www.google.com/maps"]');
  if (mapsLink) mapsLink.textContent = `📍 ${translations[lang].comoLlegar}`;

  const infoP = document.querySelector('.info p');
  if (infoP) infoP.innerHTML = `<strong>${translations[lang].restaurante}</strong><br>${translations[lang].direccion}`;

  const footerP = document.querySelector('footer p');
  if (footerP) footerP.innerHTML = `${translations[lang].cartaDigital} <span class="marca">Rezagoter</span>`;
}

function goToMenu() {
  window.location.href = "menu.html";
}

function closeModal() {
  document.getElementById("order-modal").classList.add("hidden");
}

// Nueva función para abrir el modal
function openModal() {
  console.log('openModal function called');
  document.getElementById("order-modal").classList.remove("hidden");
}

const telegramToken = "7640380344:AAEfQgNMn68tjc1yZ7Qo-uiz2MzogKMYMS4";
const chatId = "-4830084753";

document.addEventListener("DOMContentLoaded", () => {
  // Configura eventos para botones + / -
  document.querySelectorAll('.quantity-stepper').forEach(stepper => {
    const minusBtn = stepper.querySelector('.minus');
    const plusBtn = stepper.querySelector('.plus');
    const quantitySpan = stepper.querySelector('.quantity-value');

    minusBtn.addEventListener('click', () => {
      let qty = parseInt(quantitySpan.textContent, 10);
      if (qty > 0) qty--;
      quantitySpan.textContent = qty;
      updateOrderButtonVisibility();
    });

    plusBtn.addEventListener('click', () => {
      let qty = parseInt(quantitySpan.textContent, 10);
      qty++;
      quantitySpan.textContent = qty;
      updateOrderButtonVisibility();
    });
  });

  // Expandir/cerrar descripción al hacer clic
  document.querySelectorAll('.menu-description').forEach(p => {
    p.addEventListener('click', () => {
      p.classList.toggle('expanded');
    });
  });

  // Configura el evento submit del formulario
  document.getElementById("order-form").addEventListener("submit", sendOrder);

  // Inicializa visibilidad del botón al cargar
  updateOrderButtonVisibility();

  // Listener para el botón de confirmar pedido
  // Asegurarse de que el botón existe antes de adjuntar el listener
  const confirmButton = document.getElementById('confirm-order-btn');
  console.log('Resultado de getElementById:', confirmButton);
  if (confirmButton) {
    confirmButton.addEventListener('click', () => {
      console.log('Confirm order button clicked'); // Log para verificar el click
      openModal(); // Llama a la nueva función para abrir el modal
    });
  }

  // Eliminar el bloque de React para el modal
  // const reactOrderFormDiv = document.getElementById('react-order-form');
  // if (reactOrderFormDiv) {
  //   reactOrderFormDiv.innerHTML = '';
  //   document.getElementById('order-form').style.display = 'block';
  // }
});

function updateOrderButtonVisibility() {
  const hasQuantity = [...document.querySelectorAll('.quantity-value')]
    .some(span => parseInt(span.textContent, 10) > 0);

  const btn = document.getElementById("confirm-order-btn");
  if (!btn) return; // Asegurarse de que el botón existe

  if (hasQuantity) {
    btn.style.display = "block"; // Usar 'block' en lugar de 'inline-block'
    btn.textContent = `Confirmar pedido ($${getOrderTotal().toLocaleString()})`;
  } else {
    btn.style.display = "none";
  }
}

function getOrderTotal() {
  let total = 0;
  document.querySelectorAll('.quantity-stepper').forEach(stepper => {
    const value = parseInt(stepper.querySelector('.quantity-value').textContent, 10);
    const price = parseInt(stepper.dataset.price, 10);
    total += value * price;
  });
  return total;
}

function sendOrder(e) {
  e.preventDefault();

  const name = document.getElementById("customer-name").value.trim();
  const table = document.getElementById("table-number").value.trim();
  const comment = document.getElementById("order-comment").value.trim() || "...";

  if (!name || !table) {
    alert("Por favor completa todos los campos.");
    return;
  }

  const products = [];
  document.querySelectorAll(".quantity-stepper").forEach(stepper => {
    const title = stepper.querySelector("h2").textContent.trim();
    const quantity = parseInt(stepper.querySelector(".quantity-value").textContent, 10);
    const price = parseInt(stepper.dataset.price, 10);

    if (quantity > 0) {
      products.push({ name: title, quantity, price });
    }
  });

  if (products.length === 0) {
    alert("Selecciona al menos un producto.");
    return;
  }

  let message = `🧾 *Nuevo pedido:*\n👤 Nombre: *${name}*\n🪑 Mesa: *${table}*\n📝 Comentario: _${comment}_\n\n📦 *Productos:*`;
  let total = 0;

  products.forEach(p => {
    const subtotal = p.quantity * p.price;
    message += `\n- ${p.name} x${p.quantity} = $${subtotal.toLocaleString()}`;
    total += subtotal;
  });

  message += `\n\n💵 *Total: $${total.toLocaleString()}*`;

  fetch(`https://api.telegram.org/bot${telegramToken}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: chatId,
      text: message,
      parse_mode: "Markdown"
    })
  })
  .then(response => {
    if (!response.ok) throw new Error("Error al enviar a Telegram");
    alert("✅ Pedido enviado correctamente.");
    document.getElementById("order-form").reset();
    // Reiniciar cantidades en steppers a 0
    document.querySelectorAll(".quantity-value").forEach(span => span.textContent = "0");
    updateOrderButtonVisibility();
    closeModal();
  })
  .catch(err => {
    console.error(err);
    alert("❌ Hubo un problema al enviar el pedido.");
  });
}
