const translations = {
  es: {
    welcome: "Bienvenido a Vocate",
    description: `"Cultivada en la tierra, disfrutada en el alma"<br>
      Vocate nace en el corazón de Antioquia, fusionando tradición y creatividad para ofrecer una experiencia cervecera única.
      Esta bendita y refrescante cerveza artesanal destaca por su equilibrio perfecto entre cuerpo y sabor, con vibrantes notas cítricas que despiertan los sentidos.
      Con un 5% de alcohol, es ideal para quienes buscan disfrutar de una bebida ligera, pero con carácter.
      Su proceso de elaboración cuidadoso y el uso de ingredientes seleccionados garantizan una textura suave y un final limpio,
      convirtiéndola en una opción inolvidable para los amantes de la buena cerveza.`,
    price: "Precio: $13.000",
    carta: "Carta",
    llamar: "Llamar",
    comoLlegar: "Cómo llegar",
    cartaDigital: "Carta digital generada por",
    restaurante: "Vocate",
    direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
    pedir: "Pedir",
    confirmarPedido: "Confirmar pedido",
    menu: "Menú",
    nombre: "Nombre",
    mesa: "Número de mesa",
    comentario: "Comentario (opcional)",
    enviarPedido: "Enviar pedido",
    cancelar: "Cancelar",
    confirmarPedidoTitulo: "¿Confirmas tu pedido?",
    productos: {
      cerveza: {
        nombre: "Cerveza Vocate",
        descripcion: "Esta bendita y refrescante cerveza artesanal destaca por su equilibrio perfecto entre cuerpo y sabor, con vibrantes notas cítricas que despiertan los sentidos. Con un 5% de alcohol, es ideal para quienes buscan disfrutar de una bebida ligera, pero con carácter."
      },
      mango: {
        nombre: "Mango Biche",
        descripcion: "Tiritas de mango verde fresco servidas en copa, acompañadas de una rodaja de limón para resaltar su sabor ácido y refrescante. 🌱 Perfecto para abrir el apetito o disfrutar con una cerveza artesanal bien fría."
      },
      nachos: {
        nombre: "Nachos",
        descripcion: "Nachos de maíz bañados en cremosa salsa de queso cheddar derretido, coronados con rodajas de jalapeños en conserva para un toque picante irresistible. 🧀🔥 Perfectos para compartir."
      },
      mani: {
        nombre: "Mani Salado",
        descripcion: "Clásico maní crocante, ligeramente salado y perfecto para picar. Ideal como acompañamiento informal para disfrutar junto a una cerveza bien fría. 🧂 Sencillo, sabroso y siempre bienvenido."
      },
      aguacate: {
        nombre: "Aguacate relleno con ceviche de camarón",
        descripcion: "Mitad de aguacate fresco relleno con una mezcla vibrante de camarones cocidos, tomate, cebolla morada, pimentón y cilantro, todo bañado en un toque de jugo de limón. 🌊 Una explosión tropical de frescura, suavidad y textura."
      }
    }
  },
  en: {
    welcome: "Welcome to Vocate",
    description: `"Grown in the earth, enjoyed in the soul"<br>
      Vocate is born in the heart of Antioquia, blending tradition and creativity to offer a unique craft beer experience.
      This blessed and refreshing beer stands out for its perfect balance between body and flavor, with vibrant citrus notes that awaken the senses.
      With 5% alcohol, it's ideal for those seeking a light yet characterful drink.
      Its careful brewing process and selected ingredients ensure a smooth texture and clean finish,
      making it an unforgettable choice for true beer lovers.`,
    price: "Price: $13,000",
    carta: "Menu",
    llamar: "Call",
    comoLlegar: "Get Directions",
    cartaDigital: "Digital menu generated by",
    restaurante: "Vocate",
    direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
    pedir: "Order",
    confirmarPedido: "Confirm order",
    menu: "Menu",
    nombre: "Name",
    mesa: "Table number",
    comentario: "Comment (optional)",
    enviarPedido: "Send order",
    cancelar: "Cancel",
    confirmarPedidoTitulo: "Confirm your order?",
    productos: {
      cerveza: {
        nombre: "Vocate Beer",
        descripcion: "This blessed and refreshing craft beer stands out for its perfect balance between body and flavor, with vibrant citrus notes that awaken the senses. With 5% alcohol, it's ideal for those seeking a light yet characterful drink."
      },
      mango: {
        nombre: "Green Mango",
        descripcion: "Fresh green mango strips served in a cup, accompanied by a lemon slice to enhance its acidic and refreshing taste. 🌱 Perfect as an appetizer or to enjoy with a cold craft beer."
      },
      nachos: {
        nombre: "Nachos",
        descripcion: "Corn nachos covered in creamy melted cheddar cheese sauce, topped with preserved jalapeño slices for an irresistible spicy touch. 🧀🔥 Perfect for sharing."
      },
      mani: {
        nombre: "Salted Peanuts",
        descripcion: "Classic crunchy peanuts, lightly salted and perfect for snacking. Ideal as an informal accompaniment to enjoy with a cold beer. 🧂 Simple, tasty, and always welcome."
      },
      aguacate: {
        nombre: "Avocado stuffed with shrimp ceviche",
        descripcion: "Fresh avocado half filled with a vibrant mix of cooked shrimp, tomato, purple onion, bell pepper, and cilantro, all bathed in a touch of lemon juice. 🌊 A tropical explosion of freshness, smoothness, and texture."
      }
    }
  },
  de: {
    welcome: "Willkommen bei Vocate",
    description: `"In der Erde gewachsen, in der Seele genossen"<br>
      Vocate entsteht im Herzen von Antioquia und verbindet Tradition und Kreativität für ein einzigartiges Biererlebnis.
      Dieses gesegnete und erfrischende Bier zeichnet sich durch seine perfekte Balance zwischen Körper und Geschmack aus, mit lebendigen Zitrusnoten, die die Sinne wecken.
      Mit 5% Alkohol ist es ideal für diejenigen, die ein leichtes, aber charaktervolles Getränk suchen.
      Sein sorgfältiger Brauprozess und ausgewählte Zutaten garantieren eine weiche Textur und einen sauberen Abgang,
      was es zu einer unvergesslichen Wahl für echte Bierliebhaber macht.`,
    price: "Preis: $13.000",
    carta: "Karte",
    llamar: "Anrufen",
    comoLlegar: "Wegbeschreibung",
    cartaDigital: "Digitale Karte erstellt von",
    restaurante: "Vocate",
    direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
    pedir: "Bestellen",
    confirmarPedido: "Bestellung bestätigen",
    menu: "Speisekarte",
    nombre: "Name",
    mesa: "Tischnummer",
    comentario: "Kommentar (optional)",
    enviarPedido: "Bestellung senden",
    cancelar: "Abbrechen",
    confirmarPedidoTitulo: "Bestellung bestätigen?",
    productos: {
      cerveza: {
        nombre: "Vocate Bier",
        descripcion: "Dieses gesegnete und erfrischende Craft-Bier zeichnet sich durch seine perfekte Balance zwischen Körper und Geschmack aus, mit lebendigen Zitrusnoten, die die Sinne wecken. Mit 5% Alkohol ist es ideal für diejenigen, die ein leichtes, aber charaktervolles Getränk suchen."
      },
      mango: {
        nombre: "Grüne Mango",
        descripcion: "Frische grüne Mangostreifen in einer Tasse serviert, begleitet von einer Zitronenscheibe, um den säuerlichen und erfrischenden Geschmack zu verstärken. 🌱 Perfekt als Vorspeise oder zum Genießen mit einem kalten Craft-Bier."
      },
      nachos: {
        nombre: "Nachos",
        descripcion: "Maisnachos überzogen mit cremiger geschmolzener Cheddar-Käsesauce, belegt mit eingelegten Jalapeño-Scheiben für eine unwiderstehliche würzige Note. 🧀🔥 Perfekt zum Teilen."
      },
      mani: {
        nombre: "Gesalzene Erdnüsse",
        descripcion: "Klassische knusprige Erdnüsse, leicht gesalzen und perfekt zum Knabbern. Ideal als informelle Beilage zum Genießen mit einem kalten Bier. 🧂 Einfach, lecker und immer willkommen."
      },
      aguacate: {
        nombre: "Avocado gefüllt mit Garnelen-Ceviche",
        descripcion: "Frische Avocadohälfte gefüllt mit einer lebendigen Mischung aus gekochten Garnelen, Tomaten, roten Zwiebeln, Paprika und Koriander, alles in einem Hauch von Zitronensaft gebadet. 🌊 Eine tropische Explosion von Frische, Weichheit und Textur."
      }
    }
  },
  fr: {
    welcome: "Bienvenue chez Vocate",
    description: `"Cultivée dans la terre, savourée dans l'âme"<br>
      Vocate naît au cœur d'Antioquia, alliant tradition et créativité pour offrir une expérience brassicole unique.
      Cette bière bénie et rafraîchissante se distingue par son équilibre parfait entre corps et saveur, avec des notes vibrantes d'agrumes qui éveillent les sens.
      Avec 5% d'alcool, elle est idéale pour ceux qui recherchent une boisson légère mais avec du caractère.
      Son processus de brassage soigné et l'utilisation d'ingrédients sélectionnés garantissent une texture douce et une finale propre,
      en faisant un choix inoubliable pour les vrais amateurs de bière.`,
    price: "Prix: $13.000",
    carta: "Carte",
    llamar: "Appeler",
    comoLlegar: "Itinéraire",
    cartaDigital: "Carte numérique générée par",
    restaurante: "Vocate",
    direccion: "Cl. 11 #12-42, Santa Fé de Antioquia, Antioquia",
    pedir: "Commander",
    confirmarPedido: "confirmer la commande",
    menu: "Menu",
    nombre: "Nom",
    mesa: "Numéro de table",
    comentario: "Commentaire (optionnel)",
    enviarPedido: "Envoyer la commande",
    cancelar: "Annuler",
    confirmarPedidoTitulo: "Confirmer votre commande ?",
    productos: {
      cerveza: {
        nombre: "Bière Vocate",
        descripcion: "Cette bière bénie et rafraîchissante se distingue par son équilibre parfait entre corps et saveur, avec des notes vibrantes d'agrumes qui éveillent les sens. Avec 5% d'alcool, elle est idéale pour ceux qui recherchent une boisson légère mais avec du caractère."
      },
      mango: {
        nombre: "Mangue Verte",
        descripcion: "Lanières de mangue verte fraîche servies dans une coupe, accompagnées d'une tranche de citron pour rehausser son goût acide et rafraîchissant. 🌱 Parfait comme apéritif ou à déguster avec une bière artisanale bien fraîche."
      },
      nachos: {
        nombre: "Nachos",
        descripcion: "Nachos de maïs nappés d'une sauce crémeuse au fromage cheddar fondu, garnis de tranches de jalapeños marinés pour une touche épicée irrésistible. 🧀🔥 Parfait pour partager."
      },
      mani: {
        nombre: "Cacahuètes Salées",
        descripcion: "Cacahuètes croustillantes classiques, légèrement salées et parfaites pour grignoter. Idéales comme accompagnement informel à déguster avec une bière bien fraîche. 🧂 Simple, savoureux et toujours bienvenu."
      },
      aguacate: {
        nombre: "Avocat farci au ceviche de crevettes",
        descripcion: "Demi-avocat frais farci d'un mélange vibrant de crevettes cuites, tomates, oignons rouges, poivrons et coriandre, le tout baigné d'une touche de jus de citron. 🌊 Une explosion tropicale de fraîcheur, de douceur et de texture."
      }
    }
  }
};

function changeLanguage(lang) {
  localStorage.setItem("language", lang);
  updateTexts();
}

function updateTexts() {
  const lang = localStorage.getItem("language") || "es";
  const cartaButton = document.querySelector('button[onclick="goToMenu()"]');
  if (cartaButton) cartaButton.textContent = translations[lang].carta;

  const llamarLink = document.querySelector('a[href^="tel:"]');
  if (llamarLink) llamarLink.textContent = `📞 ${translations[lang].llamar}`;

  const mapsLink = document.querySelector('a[href^="https://www.google.com/maps"]');
  if (mapsLink) mapsLink.textContent = `📍 ${translations[lang].comoLlegar}`;

  const infoP = document.querySelector('.info p');
  if (infoP) infoP.innerHTML = `<strong>${translations[lang].restaurante}</strong><br>${translations[lang].direccion}`;

  const footerP = document.querySelector('footer p');
  if (footerP) footerP.innerHTML = `${translations[lang].cartaDigital} <span class="marca">Rezagoter</span>`;

  // Actualizar textos en menu.html
  const menuTitle = document.querySelector('.menu-header h1');
  if (menuTitle) menuTitle.textContent = translations[lang].menu;

  // Actualizar el botón de confirmar pedido con el total
  const confirmOrderBtn = document.getElementById('confirm-order-btn');
  if (confirmOrderBtn) {
    const total = getOrderTotal();
    confirmOrderBtn.textContent = `${translations[lang].confirmarPedido} ($${total.toLocaleString()})`;
  }

  // Actualizar textos del modal
  const modalTitle = document.querySelector('.modal-content h2');
  if (modalTitle) modalTitle.textContent = translations[lang].confirmarPedidoTitulo;

  const nameLabel = document.querySelector('label[for="customer-name"]');
  if (nameLabel) nameLabel.textContent = translations[lang].nombre;

  const tableLabel = document.querySelector('label[for="table-number"]');
  if (tableLabel) tableLabel.textContent = translations[lang].mesa;

  const commentLabel = document.querySelector('label[for="order-comment"]');
  if (commentLabel) commentLabel.textContent = translations[lang].comentario;

  const sendOrderBtn = document.getElementById('send-order-btn');
  if (sendOrderBtn) sendOrderBtn.textContent = translations[lang].enviarPedido;

  const cancelBtn = document.querySelector('.modal-content button[onclick="closeModal()"]');
  if (cancelBtn) cancelBtn.textContent = translations[lang].cancelar;

  // Actualizar nombres y descripciones de productos
  const menuItems = document.querySelectorAll('.menu-item');
  menuItems.forEach(item => {
    const titleElement = item.querySelector('.menu-info h2');
    const descElement = item.querySelector('.menu-description');
    
    if (titleElement && descElement) {
      const productKey = getProductKey(titleElement.textContent.trim());
      if (productKey && translations[lang].productos[productKey]) {
        titleElement.textContent = translations[lang].productos[productKey].nombre;
        descElement.textContent = translations[lang].productos[productKey].descripcion;
      }
    }
  });
}

function getProductKey(spanishName) {
  const productMap = {
    'Cerveza Vocate': 'cerveza',
    'Mango Biche': 'mango',
    'Nachos': 'nachos',
    'Mani Salado': 'mani',
    'Aguacate relleno con ceviche de camarón': 'aguacate'
  };
  return productMap[spanishName];
}

function goToMenu() {
  const currentLang = localStorage.getItem("language") || "es";
  window.location.href = `menu.html?lang=${currentLang}`;
}

function closeModal() {
  document.getElementById("order-modal").classList.add("hidden");
}

function openModal() {
  document.getElementById("order-modal").classList.remove("hidden");
}
const telegramToken = "7640380344:AAEfQgNMn68tjc1yZ7Qo-uiz2MzogKMYMS4";
const chatId = "-4861996433"


document.addEventListener("DOMContentLoaded", () => {
  // Configura eventos para botones + / -
  document.querySelectorAll('.quantity-stepper').forEach(stepper => {
    const minusBtn = stepper.querySelector('.minus');
    const plusBtn = stepper.querySelector('.plus');
    const quantitySpan = stepper.querySelector('.quantity-value');

    minusBtn.addEventListener('click', () => {
      let qty = parseInt(quantitySpan.textContent, 10);
      if (qty > 0) qty--;
      quantitySpan.textContent = qty;
      updateOrderButtonVisibility();
    });

    plusBtn.addEventListener('click', () => {
      let qty = parseInt(quantitySpan.textContent, 10);
      qty++;
      quantitySpan.textContent = qty;
      updateOrderButtonVisibility();
    });
  });

  document.querySelectorAll('.menu-description').forEach(p => {
    p.addEventListener('click', () => {
      p.classList.toggle('expanded');
    });
  });

  // Botón para confirmar pedido abre el modal
  const confirmButton = document.getElementById('confirm-order-btn');
  if (confirmButton) {
    confirmButton.addEventListener('click', openModal);
  }

  // Botón dentro del modal que realmente envía el pedido
  const sendBtn = document.getElementById('send-order-btn');
  if (sendBtn) {
    sendBtn.addEventListener('click', sendOrder);
  }

  updateOrderButtonVisibility();
});

function updateOrderButtonVisibility() {
  const hasQuantity = [...document.querySelectorAll('.quantity-value')]
    .some(span => parseInt(span.textContent, 10) > 0);

  const btn = document.getElementById("confirm-order-btn");
  if (!btn) return;

  const lang = localStorage.getItem("language") || "es";
  if (hasQuantity) {
    btn.style.display = "block";
    const total = getOrderTotal();
    btn.textContent = `${translations[lang].confirmarPedido} ($${total.toLocaleString()})`;
  } else {
    btn.style.display = "none";
  }
}

function getOrderTotal() {
  let total = 0;
  document.querySelectorAll('.quantity-stepper').forEach(stepper => {
    const value = parseInt(stepper.querySelector(".quantity-value").textContent, 10);
    const price = parseInt(stepper.dataset.price, 10);
    total += value * price;
  });
  return total;
}

function sendOrder(e) {
  if (e) e.preventDefault();

  const name = document.getElementById("customer-name").value.trim();
  const table = document.getElementById("table-number").value.trim();
  const comment = document.getElementById("order-comment").value.trim() || "...";

  if (!name || !table) {
    alert("Por favor completa todos los campos.");
    return;
  }

  const products = [];
  document.querySelectorAll(".quantity-stepper").forEach(stepper => {
    const menuItem = stepper.closest('.menu-item');
    if (!menuItem) return;

    const titleElement = menuItem.querySelector(".menu-info h2");
    if (!titleElement) return;

    const title = titleElement.textContent.trim();
    const quantity = parseInt(stepper.querySelector(".quantity-value").textContent, 10);
    const price = parseInt(stepper.dataset.price, 10);

    if (quantity > 0) {
      products.push({ name: title, quantity, price });
    }
  });

  if (products.length === 0) {
    alert("Selecciona al menos un producto.");
    return;
  }

  let message = `🧾 Nuevo pedido:
👤 Nombre: ${name}
🪑 Mesa: ${table}
📝 Comentario: ${comment}

📦 Productos:

`;

  let total = 0;

  products.forEach(p => {
    const subtotal = p.quantity * p.price;
    message += `- ${p.name} x${p.quantity} = $${subtotal.toLocaleString()}\n`;
    total += subtotal;
  });

  message += `💵 Total: $${total.toLocaleString()}`;

  fetch(`https://api.telegram.org/bot${telegramToken}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: chatId,
      text: message,
    })
  })
  .then(response => {
    if (!response.ok) throw new Error("Error al enviar a Telegram");
    alert("✅ Pedido enviado correctamente.");
    document.getElementById("order-form").reset();
    document.querySelectorAll(".quantity-value").forEach(span => span.textContent = "0");
    updateOrderButtonVisibility();
    closeModal();
  })
  .catch(err => {
    console.error(err);
    alert("❌ Hubo un problema al enviar el pedido.");
  });
}
